fix: correct outdated Next.js docs and example
t3-oss/t3-env pull request #293
Opened 2024-12-14 20:07 UTC by TobyDS

jiti no longer uses the default export or the `jiti()` function. As such I have update the documentation to use the correct import: `import { createJiti } from "jiti"`, and the suggested replacement for the `jiti()` function: `await jiti.import()`. 

I also found that the documentation and example differed in the constuction of the path inside the `createJiti()` function. As such I have edited the documentation and the example to match each other to avoid confusion. I oped to use the syntax from the example: `const jiti = createJiti(new URL(import.meta.url).pathname)` as it doesn't require importing a function from node:url, which is currently the method used in the docs.

2025-01-14 05:38 UTC, techysiddhant commented
Thanks for this i'm searching regarding this and found this

2025-01-25 12:22 UTC, juliusmarminge commented
> const jiti = createJiti(new URL(import.meta.url).pathname) as it doesn't require importing a function from node:url, which is currently the method used in the docs

This is not cross-platform compatible

2025-01-25 12:22 UTC, juliusmarminge requested changes

2025-01-25 12:22 UTC, juliusmarminge commented on docs/src/app/docs/nextjs/page.mdx
> +const jiti = createJiti(new URL(import.meta.url).pathname);
> const jiti = createJiti(new URL(import.meta.url).pathname) as it doesn't require importing a function from node:url, which is currently the method used in the docs

This is not cross-platform compatible

2025-01-25 14:10 UTC, juliusmarminge commented
added note in docs to use jiti 1 since many have reported issues with v2

2025-01-25 14:10 UTC, closed without merging