Codeblock icon fix
t3-oss/t3-env pull request #40
Opened 2023-04-30 17:50 UTC by chungweileong94

Fix #34 

Fixed codeblock overlapping icon caused by the recent fix from #32. 

As the CSS fix from #32 (shown below), will always apply to element that has `data-theme`.
```css
[data-theme="light"] {
  @apply block dark:hidden;
}

[data-theme="dark"] {
  @apply hidden dark:block;
}
``` 

However, the language icon works slightly different, where the icon will only show if the title is present. So, the solution is to handle the hide/show separately.

2023-04-30 18:51 UTC, juliusmarminge requested changes
Looks good - dont need changesets on docs though

2023-04-30 18:51 UTC, juliusmarminge commented on .changeset/thin-bats-relax.md
Delete

2023-05-01 02:23 UTC, chungweileong94 commented on .changeset/thin-bats-relax.md
Done!

2023-05-01 09:48 UTC, juliusmarminge approved these changes

2023-05-01 09:49 UTC, merged