update zod and fix zod import error in core
t3-oss/t3-env pull request #67
Opened 2023-05-18 16:57 UTC by Cliftonz

This is to fix issue #66 
Let me know if I need to fix or change anything.

2023-05-21 14:13 UTC, chungweileong94 commented
Hmm... interesting, there's a default export from zod, probably because of some build tool problem?
![image](https://github.com/t3-oss/t3-env/assets/15154097/43bccd52-2b4f-4c6e-9931-6b189807d0c9)

But anyway, I much prefer named import personally.

2023-05-22 15:23 UTC, Cliftonz commented
@chungweileong94 anything I need to do to help this go forward?

2023-05-22 16:03 UTC, chungweileong94 commented
> @chungweileong94 anything I need to do to help this go forward?

@juliusmarminge

2023-05-22 17:06 UTC, juliusmarminge requested changes

2023-05-22 17:06 UTC, juliusmarminge commented on packages/core/package.json
> +    "zod": "^3.21.0"
Revert all of these. I dont want to bump this over the peerDep limit so we dont accidentally use new fancy festures

2023-05-22 17:06 UTC, juliusmarminge commented on packages/core/index.ts
> +  if (!parsed.success) {
Revert. For some reason just the ! operator doesnt work for some. We've gotten issues in create-t3-app with it instead of explicit === false

2023-05-22 19:54 UTC, juliusmarminge requested changes

2023-05-22 19:54 UTC, juliusmarminge commented on pnpm-lock.yaml
> -        version: 3.20.2
checkout the lockfile to main to revert it completely. now we actually bumped it anyways.

2023-05-23 19:23 UTC, Cliftonz commented
All extraneous changes have been revert, thank you for your patience @juliusmarminge !

2023-05-23 19:23 UTC, juliusmarminge approved these changes
Thanks

2023-05-23 19:29 UTC, merged